### ISSUE TITLE
Record lectures

### ISSUE THREAD

**Issue by christinasunnegardh** [KTH/devops-course#318] opened 2020-03-17 08:36 UTC
Could the lectures please be recorded to be downloaded?

My internet is unstable and makes the quality of the stream extremely low (unwatchable at times), which could be resolved by just downloading them afterwards instead.

Thank you!

PS: Philip Haller in POPL (DD2481) had a really good setup where he shared the screen and read questions from the chat directly. It was much appreciated :)

**Comment by SophieHYe** [comment] 2020-03-17 09:16
Hi,

Thanks for creating the issue and bringing the discussion.
As discussed during the lecture, we decided not to record lectures because we want to keep all conversations that occur during the lecture in the context of the lecture and not take the risk of having statements out of context. 
You can join the lectures remotely from Zoom (see  #316 ). But we will provide lecture slides in Github. But no slides for the first lecture. 

For more information, please read "remote participation" in the ReadMe. Thanks!

**Comment by christinasunnegardh** [comment] 2020-03-17 09:51
Hi Sophie!

Thank you for more information!

As I'm guessing the school will close tomorrow (😞), I assume there will only be remote lectures from now on.

Therefore, I would like to draw attention to that questions on Zoom can be asked **anonymously** (https://support.zoom.us/hc/en-us/articles/203686015-Getting-Started-with-Question-Answer). This means that no students need to worry about being quoted out of context even when the lectures are recorded. I would also like to add that I’m more worried about being quoted out of context if the **full** lecture is **not** recorded, as one student can record only a small part and then there is no proof of the full conversation.

As my internet is unstable at one of the places I live at, I will not be able to fully watch the lectures if they are not recorded so they can be downloaded afterwards. This means that under the circumstances, I will not be able to take part of the lectures.

This makes me worried and I hope you will re-consider recording the lectures!

Thank you 🙏

**Comment by balwes** [comment] 2020-03-17 10:56
There's no risk. Simply state in the readme that you cannot use quotes from lectures.

**Comment by Paul-Philip** [comment] 2020-03-17 13:30
Ironically 15 minutes after @monperrus stating that the lectures will not be recorded there was an internet blackout from some internet providers in the Stockholm region and I missed 15 minutes of the presentation today. [SVT-news](https://www.svt.se/nyheter/inrikes/driftstorningar-hos-flera-internetleverantorer)

Just in case of something unexpected happening I agree that it would really be great if there would be recordings of the lectures available.

**Comment by Pontus-Broberg** [comment] 2020-03-17 18:01
Now that all of KTH is closed down and all of the work will be done remotely, I really hope you reconsider your decision about not releasing recordings of the lectures. 

Everyday life is already really uncertain as it is. Knowing that lectures could be watched on-demand would give everyday life some much-needed stability during this period, in my opinion.

**Comment by SophieHYe** [comment] 2020-03-17 19:17
Hi all,

Thank you for your feedback and we fully understand the current situation and your worry.
As we did not record the first lecture, if you have any questions, you are welcome to create an issue or send us email. We will reconsider and discuss this lecture recording issue.

**Comment by axelkennedal** [comment] 2020-03-17 21:06
I would also appreciate if you would record the lectures

**Comment by monperrus** [comment] 2020-03-18 05:56
This is an option that will be considered under the following three conditions:

* when the guest lecturer agrees for it
* when there is not enough written resources that cover the same material as in the spoken presentation
* if the hardware and software used for videoconferencing allow for it and do actually work (best effort basis, no guarantee).

Best regards,

--Martin Monperrus

**Comment by rarkins** [comment] 2020-03-18 07:05
@monperrus I consent to having my guest lecture next week recorded

**Comment by SophieHYe** [comment] 2020-03-20 14:37
Hi all,
We will record the lecture next week with the Zoom recording function.

**Comment by veggiemonk** [comment] 2020-03-21 22:31
@monperrus I consent to having my guest lecture recorded and publicly available on the internet if the authority of the course permits it.

**Comment by SophieHYe** [comment] 2020-03-24 17:57
Dear all, for today's lecture (March 24), we used the recording feature of Zoom, which unfortunately yielded no usable file. Our root cause analysis suggests that the length of the recording (more than 3 hours) is too much. Sorry about that!  Next week, we'll try to split the recording into smaller chunks.

**Comment by SophieHYe** [comment] 2020-03-31 12:32
Video of the recorded lecture at week 3 (March 31): https://kth.box.com/s/sv5p3j6abo8a90twqwanxpmkyv0u80yo

**Comment by SophieHYe** [comment] 2020-04-27 20:12
The videos can be found #316. I am closing this PR now.

**Closed by SophieHYe** 2020-04-27 20:12 UTC
Labels: lecture videos, question
